name = "monopoly-backend"
main = "src/worker.mjs"
compatibility_date = "2025-08-01"

[durable_objects]
bindings = [{ name = "ROOMS", class_name = "Room" }]

[[migrations]]
tag = "v1"
new_classes = ["Room"]
