name: Deploy Cloudflare Worker (backend)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}   # lets you run it manually from the Actions tab

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Publish with Wrangler
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: backend        # wrangler.toml lives here
          command: deploy
