name: Deploy Cloudflare Worker (backend)

on:
  push:
    branches: [ "main" ]   # change if your default branch isn't main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Publish with Wrangler
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: backend        # <-- IMPORTANT: wrangler.toml is in /backend
          command: deploy
